service: challenge-culqi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    src/**/!(*.spec).js
  exclude:
    - node_modules/**/*

functions:
  verifyToken:
    handler: src/auth/infrastructure/handlers/auth.verifyToken

  generateToken:
    handler: src/generate-token/infrastructure/handlers/generate-token.generateToken
    events:
      - http:
          path: tokens
          method: post
          cors: true
          authorizer:
            name: verifyToken

  getCard:
    handler: src/card/infrastructure/handlers/card.getCard
    events:
      - http:
          path: card/token/{token}
          method: get
          cors: true
          authorizer:
            name: verifyToken
          request:
            parameters:
              paths:
                token: true

