service: challenge-culqi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    src/**/!(*.spec).js
  exclude:
    - node_modules/**/*

functions:
  verifyToken:
    handler: src/auth/infrastructure/handlers/auth.verifyToken
    description: validate Bearer token with format pk

  generateToken:
    handler: src/generate-token/infrastructure/handlers/generate-token.generateToken
    description: generate token for save card
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: r3d1s_3E2
    events:
      - http:
          path: tokens
          method: post
          cors: true
          authorizer:
            name: verifyToken

  getCard:
    handler: src/card/infrastructure/handlers/card.getCard
    description: return public information of card
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: r3d1s_3E2
    events:
      - http:
          path: card/token/{token}
          method: get
          cors: true
          authorizer:
            name: verifyToken
          request:
            parameters:
              paths:
                token: true

